version: '2'
services:
  producer1:
     image: producer
     build: ./producer
     environment:
      - PORT=8080
     ports:
      - "8080:8080"
     volumes:
      - ./config:/usr/src/app/config:ro
  consumer1:
     image: consumer
     build: ./consumer
     volumes:
       - ./config:/usr/src/app/config:ro
  consumer2:
      image: consumer
      build: ./consumer
      volumes:
       - ./config:/usr/src/app/config:ro
