version: '2'
services:
  zookeeper:
    image: appcelerator/zookeeper:latest
    ports:
     - "2181:2181"
     - "2888:2888"
     - "3888:3888"
  kafka:
    image: dkatona/docker-kafka:latest
    hostname: kafka
    ports:
     - "9092"
    environment:
     - TOPIC_LIST=notifications:24:1
     - ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
     - zookeeper
